version: "3.0"
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins
    restart: always
    volumes:
      - jenkins_home:/var/jenkins_home
      - docker_sock:/var/run/docker.sock
  postgres:
    container_name: postgres
    image: postgres:9.6
    networks:
      - jenkins
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonarpasswd
    volumes:
      - postgres_data:/var/lib/postgresql/data
  sonarqube:
    container_name: sonarqube
    image: sonarqube:lts
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - jenkins
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonarpasswd
      SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar"
    volumes:
      - SonarQube_data:/opt/SonarQube/data
      - SonarQube_extensions:/opt/SonarQube/extensions
      - SonarQube_logs:/opt/SonarQube/logs
    depends_on:
      - postgres

networks:
  jenkins:
    driver: bridge

volumes:
  jenkins_home:
    external: true
  docker_sock:
    external: true
  postgres_data:
    external: true
  SonarQube_data:
    external: true
  SonarQube_extensions:
    external: true
  SonarQube_logs:
    external: true